# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# If you are using Rails 5.2 or newer, consider using the
# encrypted credentials feature described here:
# http://edgeguides.rubyonrails.org/security.html#custom-credentials

development:
  domain_name: example.com
  secret_key_base: a3b44f92881b1e0efdec21780f3018574d75659baa8df6cfe7c6bd4c7a50d22a2a871d1ca07d1e013756cda9be0a555fd9a9b047d9c4a98903c60bcd36947f08
#  workspace_id: <%= ENV["WORKSPACE_ID"] %>
  workspace_id: e316ed26-3f7e-4c88-b26b-97c87e7c2b5d
#  fm_workspace: <%= ENV["FM_WORKSPACE"] %>
  fm_workspace: e316ed26-3f7e-4c88-b26b-97c87e7c2b5d
#  customer_jwt_secret: <%= ENV["CUSTOMER_JWT_SECRET"] %>
  customer_jwt_secret: 24db2224-9afc-4b8x-yeex-e1fe567c7564
#  fm_api_key: <%= ENV["FM_API_KEY"] %>
  fm_api_key: c9a6b772-cdc4-4f4x-y09x-072daa375778

test:
  domain_name: example.com
  secret_key_base: very_long_random_string
  workspace_id: <%= ENV["WORKSPACE_ID"] %>
  fm_workspace: <%= ENV["FM_WORKSPACE"] %>
  customer_jwt_secret: <%= ENV["CUSTOMER_JWT_SECRET"] %>
  fm_api_key: <%= ENV["FM_API_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  workspace_id: <%= ENV["WORKSPACE_ID"] %>
  fm_workspace: <%= ENV["FM_WORKSPACE"] %>
  customer_jwt_secret: <%= ENV["CUSTOMER_JWT_SECRET"] %>
  fm_api_key: <%= ENV["FM_API_KEY"] %>
